[package]
name = "rumblr"
version = "0.1.0"
authors = ["doomy"]

[dependencies]
hyper = "0.10.12"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
oauthcli = "2.0.0-beta-1"
quick-error = "1.2.0"

[[example]]
name = "test_methods"