[package]
name = "rumblr"
version = "0.1.0"
authors = ["doomy"]

[dependencies]
hyper = "0.12.10"
hyper-tls = "*"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
oauthcli = "2.0.0-beta-1"

[[example]]
name = "test_methods"